<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9dxffug\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9dxffug/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9dxffug.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9dxffug\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container9dxffug\appDevDebugProjectContainer([
    'container.build_hash' => '9dxffug',
    'container.build_id' => 'aeea779d',
    'container.build_time' => 1551509575,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9dxffug');
